"""Fix image_url field, add average_rating

Revision ID: 87aef042fe6e
Revises: 8ea149e893eb
Create Date: 2025-06-25 15:27:13.542535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87aef042fe6e'
down_revision = '8ea149e893eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('average_rating', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('average_rating')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
